### PR TITLE
Add prefetch count to registerRequeueConsumerOf

### PR DESCRIPTION
**Pull request by Andrea**
Co-authored-by: Andrew Gee <andrew.gee@itv.com>

### CODE REVIEW

**Comment by mcarolan** [comment]
Can't accept without a curry christmas pun

**Comment by andrewgee** [comment]
Not lentil you accept our code in principle

**Comment by Andrea** [comment]
Fair enough, :santa: :feet:  is coming to town?

**Comment by mcarolan** [comment]
LGTM, thanks for pun

**Pull request closed without merging**
