### PR TITLE
Adding a function for the final failure when requeuing

### PR DESCRIPTION
**Pull request by saavj**
Hey people,

We have a need to publish a message when a message has Deadlettered, but this became tricky when we were Requeuing. This PR allows us to pass in a function that will only be used when the retry for a Requeues meesage has run out, and the message will be Deadlettered. 

Thanks!

### CODE REVIEW

**Comment by chrischivers** [comment]
Looks good to me, but should there be a test for this?

**Comment by BeniVF** [comment]
Agreed with @chrischivers! @saavj could you add some unit tests?

**Comment by BeniVF** [comment]
one question @saavj, if the function is pure, what can you do? Requeue/Ack that does not seem the right behaviour.

- Requeue: it is not correct because the requeue policy has been broken.
- Ack: it is ignore the problem, that does not seem correct to me.

**Comment by saavj** [comment]
Hey thanks both @chrischivers @BeniVF Just writing a test now sorry!! @BeniVF yea this doesn't really make sense for pure functions but we had impure plans for this 🙈

**Comment by BeniVF** [comment]
Then you should use F[_]

**Comment by BeniVF** [comment]
Basically instead of `onFinalFailure: () => ConsumeAction` it should be `onFinalFailure: F[ConsumeAction]`

**Pull request merged**
